name: Publish to RubyGems
on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Build Gem
        run: gem build -o patch_ruby.gem patch_ruby.gemspec

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Run RSpec
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: bundle exec rspec

      - name: Push to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: gem push patch_ruby.gem

