name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Build Gem
        run: gem build -o patch_ruby.gem patch_ruby.gemspec

      - name: Run RSpec
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: bundle exec rspec
